---
version: "3.7"

services:
  tf:
    working_dir: /app/${WORKING_DIR}
    entrypoint: ${ENTRYPOINT}
    image: hashicorp/terraform:${TERRAFORM_VERSION_TAG}
    volumes:
      - ./terraform:/app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
